---
title: "141SL Project"
author: "Kathy Fu, Kristee Song, Bella Lee, Joy Harjanto"
date: "5/6/2019"
output: html_document
---

Text-Mining Survey Response Keywords
```{r}
#clear memory for second part
rm(list=ls())

#read in only Dashboard, Market Results, & Program Evals
library(readr)
setwd("~/Documents/141/ALCDataFiles_anonymized")
folder <- list.files(path = "~/Documents/141/ALCDataFiles_anonymized", pattern = "(Dash|Market|Program).*\\.csv$", full.names = F)
for (i in 1: length(folder)){
  assign(folder[i],read.csv(paste(folder[i])))
}

# What are the odds of someone answering an open-ended? What factors (race, gender, country, continuing student, phD student, a certain race) contribute to higher odds?

#Recode Program Evals Open Ended to 0 and 1
e <- .GlobalEnv
progevals <- ls(pattern = "Program.*\\.csv$", envir = e)
library(dplyr)

for (i in 1:length(progevals)){
  #identifiers <- c("about","changes","comment")
  #for (word in identifiers){
  # if there are progevals with "about":
  about <- agrep("about", colnames(e[[progevals[i]]]),ignore.case = TRUE)
  if (length(about) != 0){
    # The "about" questions are open-ended
    df <- e[[progevals[i]]][,(agrep("about", colnames(e[[progevals[i]]]),ignore.case = TRUE))]
    df <- df %>% replace(.!="NULL", NA)
    df <- lapply(lapply(df, is.na),as.numeric)
    #replace the original column for 0s and 1s
    for (j in 1:length(df)){
      columntitle <- names(df[j])
     e[[progevals[i]]][columntitle] <- df[j]
    }
  }
  
  changes<- grep("changes", colnames(e[[progevals[i]]]),ignore.case = TRUE)
  if (length(changes) != 0){
    # The "changes" questions are open-ended
    df <- e[[progevals[i]]][,(grep("changes", colnames(e[[progevals[i]]]),ignore.case = TRUE))]
    df <- df %>% replace(.!="NULL", NA)
    df <- lapply(lapply(df, is.na),as.numeric)
    #replace the original column for 0s and 1s
    for (j in 1:length(df)){
      columntitle <- names(df[j])
     e[[progevals[i]]][columntitle] <- df[j]
    }
  }
  
  comment <- grep("comment", colnames(e[[progevals[i]]]),ignore.case = TRUE)
  if (length(comment) != 0){
    # The "comment" questions are open-ended
    df <- e[[progevals[i]]][,(grep("comment", colnames(e[[progevals[i]]]),ignore.case = TRUE))]
    df <- df %>% replace(.!="NULL", NA)
    df <- lapply(lapply(df, is.na),as.numeric)
    #replace the original column for 0s and 1s
    for (j in 1:length(df)){
      columntitle <- names(df[j])
     e[[progevals[i]]][columntitle] <- df[j]
    }
  }
}


#Adjust Quarter to QuarterYear and QuarterHalf
library(stringr)
get_quarter <- function(dataframe) {
  quarter <- rep(NA, 2)
  quarter[1] <- substring(str_extract_all(dataframe$Quarter, "_\\w{4,6}_\\d{4}"), 2) %>% str_replace(., "_", " ")
  quarter[2] <- str_extract_all(dataframe$Quarter, "_\\w{3}_") %>% substring(.,2,4)
  quarter
}

progevals <- ls(pattern = "Program.*\\.csv$", envir = e)

for(i in length(progevals)) {
  e[[progevals[i]]]$QuarterYear <- get_quarter(e[[progevals[i]]])[1]
  e[[progevals[i]]]$QuarterHalf <- get_quarter(e[[progevals[i]]])[2]
  e[[progevals[i]]] <- e[[progevals[i]]][,-which(colnames(e[[progevals[i]]]) == "Quarter")]
}

#merge each file now with Dashboard & Market to get more factors
market <- ls(pattern = "Market.*\\.csv$", envir = e)
for (i in length(market)){
  file <- merge(Dashboard_24_export.csv, e[[market[i]]], by = "ID_anon")
  if(nrow(file) != 0){
    for (j in length(progevals)){
      e[[progevals[j]]] <- merge(file, e[[progevals[j]]], by = "ID_anon")
      e[[progevals[j]]] <- merge(file, e[[progevals[j]]], by = "ID_anon", all.y = TRUE)
    }
  }
}


#logistic regression of the resulting data: 
```

```{r}
colnames(Program_Evaluations_33_export.csv)
sum(Program_Evaluations_33_export.csv[['ID_anon']] %in% file[['ID_anon']])
sum(Program_Evaluations_34_export.csv[['ID_anon']] %in% file[['ID_anon']])
sum(Program_Evaluations_46_export.csv[['ID_anon']] %in% file[['ID_anon']])
sum(Program_Evaluations_80_export.csv[['ID_anon']] %in% file[['ID_anon']])
sum(Program_Evaluations_81_export.csv[['ID_anon']] %in% file[['ID_anon']])
sum(Program_Evaluations_82_export.csv[['ID_anon']] %in% file[['ID_anon']])
sum(Program_Evaluations_92_export.csv[['ID_anon']] %in% file[['ID_anon']])
sum(Program_Evaluations_93_export.csv[['ID_anon']] %in% file[['ID_anon']])


```

```{r}
Reduce(function(x,y) merge(x,y),list())
```
Popular Elective Course Patterns
- What classes did your elective preference
```{r}
#clear memory for second part
rm(list=ls())

#read in only Dashboard, Elective_Preferences Intermediate & Advanced
folder <- list.files(path = "~/Documents/141/ALCDataFiles_anonymized", pattern = "(Dash|Elective).*\\.csv$", full.names = F)
for (i in 1: length(folder)){
  assign(folder[i],read.csv(paste(folder[i])))
}



#wordcloud
library("wordcloud")
set.seed(135719)


#textmining
library(tm)
```
